### ISSUE TITLE
Develop a "bucket" container that can read in configurations based on URL-passed ID

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#2]
A web page is developed that can can be passed an ID in the URL, and the corresponding StoryRAMP product loads.

The bucket needs to:

- [x] Read a JSON configuration file
- [x] [Display a slide with two panels (that flow vertically in mobile/narrow resolutions)](#35)
- [x] Display a slide with one panel (using max width)
- [x] [Display text panels](#34)
- [x] Display multimedia panels(just images for now)
- [x] Display multimedia slide with a gallerys
- [x] Display an interactive map slide
- [x] Display DQV chart slides

We also need to:
- [x] [Determine the folder structure of a RAMP product](#33)

Checkboxes above should link to individual issues.

**Comment by dan-bowerman** [comment]
The bucket needs to:

- [ ] Read a JSON configuration file
- [ ] Display a slide with two panels (that flow vertically in mobile/narrow resolutions)
- [ ] Display a slide with one panel (using max width)
- [ ] Display text panels
- [ ] Display multimedia panels(just images for now)
- [ ] Display multimedia slide with a gallerys
- [ ] Display an interactive map slide
- [ ] Display DQV chart slides

Checkboxes will link to individual issues.
