### ISSUE TITLE
Migrate existing STB Products to RAMP4/Vue3

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#383]
This issue is to take inventory of, upgrade, and prepare for release the 15+ Storylines products from STB that are still leveraging RAMP3. 

2023-10-16: Upgrading this to an EPIC! 

- [x] @yileifeng - https://github.com/ramp4-pcar4/story-ramp/issues/389
- [x] @spencerwahl - https://github.com/ramp4-pcar4/story-ramp/issues/390
- [x] @dnlnashed - https://github.com/ramp4-pcar4/ramp4-pcar4/issues/1908
- [x] @dan-bowerman - Connect with clients and let them know about the migration/not to touch anything
- [x] @mohsin-r - https://github.com/ramp4-pcar4/storylines-editor/pull/225
- [x] @mohsin-r - https://github.com/ramp4-pcar4/story-ramp/pull/377
- [x] @dan-bowerman - https://github.com/ramp4-pcar4/story-ramp/issues/385
- [ ] ~@yileifeng - https://github.com/ramp4-pcar4/story-ramp/issues/381~
- [ ] ~@yileifeng - https://github.com/ramp4-pcar4/story-ramp/issues/378~

Latest versions (and IDs) of the RAMP3-based Storylines products are in Azure DevOps: https://tfs.int.ec.gc.ca/tfs/DC/BeSD_Geospatial_Data/_git/RAMP%20Storylines

**Comment by dan-bowerman** [comment]
Duplicate of https://github.com/ramp4-pcar4/story-ramp/issues/383, https://github.com/ramp4-pcar4/story-ramp/issues/384. This is more appropriately left in the story-ramp repo.

**Comment by dan-bowerman** [comment]
One consideration for STB Storylines is that a few of them have time-slider support. We will need to reproduce this functionality in RAMP4 before we are ready to migrate the Production applications.
