### ISSUE TITLE
RAMP3 rollup

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#66]
- [x] https://github.com/fgpv-vpgf/fgpv-vpgf/issues/4002
- [x] https://github.com/fgpv-vpgf/fgpv-vpgf/issues/4001
- [x] https://github.com/fgpv-vpgf/fgpv-vpgf/issues/4004
- [x] https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3972
- [x] https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3911
- [x] https://github.com/ramp4-pcar4/story-ramp/issues/67
