### ISSUE TITLE
Ready for Release - v1.0

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#91]
- [ ] ~~#15 Document process for STB to publish datasets consistently~~
- [x] #19 Work with Security to include StoryRAMP in existing IMODS agreement
- [x] #25 WCAG: Break out accessibility report into Development Tasks
- [x] #29 Test on mobile resolutions/devices 
- [x] #79 Oil Sands Extraction StoryRAMP product Comms review
- [x] #82 WebTrends integration
- [x] #87 Setup dedicated Azure App Service and pipeline 
- [x] #88 Name this application!
- [ ] #90 jMeter/BlazeMeter load testing
- [ ] #100 Add HTML History mode
- [x] #20 Deployment plan with WIG/CCoE
- [x] #97 Mobile flow
